const Constants = {
  KAPREKAR_CONSTANT: 6174,
  KAPREKAR_LOWER_LIMIT: 1000,
  KAPREKAR_UPPER_LIMIT: 9999,
  INITIAL_NUMBER_OF_ITERATION: 0,
  DIGITS_OF_KAPREKAR_CONSTANT: 4,
};

export default Constants;
